# Umi4 errorThrower不执行

`import type { RequestConfig } from '@umijs/max';

export const request: RequestConfig = {
timeout: 2000,
errorConfig: {
// 错误抛出
errorThrower: (res) => {
console.log(res);
},
// 错误接收及处理
errorHandler: (error: any) => {
console.log(error);
},
},
// 请求拦截器
requestInterceptors: [
(url, options) => {
const headers: any = { ...options.headers };
const token = localStorage.getItem('access_token');
if (token) {
headers['x-token'] = token;
}
return { url, options: { ...options, headers } };
},
],
// 响应拦截器
responseInterceptors: [
(response) => {
// 拦截响应数据，进行个性化处理
const { data } = response;
console.log(data);
return response;
},
],
};

export default request;
`

<img width="490" alt="image" src="https://user-images.githubusercontent.com/24239032/177243358-d5613349-8cb0-4393-bb84-ccf2e4fb078a.png">

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/24239032/177262981-0c4b1b9f-1d96-4909-a704-7711637f4cb0.png">
此报错只执行了errorHandler
  
  
  
  ## Ggmid
  
  > 
我也遇到了这个问题，还是直接在拦截器直接做吧

## geyitu

> >
>
> 我也遇到了这个问题，还是直接在拦截器直接做吧

我也遇到了

## dongxiaoyong009

正在对项目做升级，也遇到这个问题

## dongxiaoyong009

![image](https://user-images.githubusercontent.com/13757451/184318375-f9da61d6-5426-41f1-b9a4-999f880e410d.png)
不执行的原因在这里, 老老实实在响应拦截器里处理一下数据格式吧，至少加一个 success字段

## zeyueguo

这样转换一下就可以进入errorThrower

```
  responseInterceptors: [
    (response: AxiosResponse) => {
      const { code: errorCode, message: errorMessage, data } = response.data;
      response.data = {
        errorCode,
        errorMessage,
        data,
        success: errorCode === 0,
      };
      return response;
    },
  ]


  ## zengxpang

  我也遇到这个问题，而且我的data里面是有success 字段的，但是为false的时候也是不走该逻辑。而且在响应拦截里面重新处理success字段也是无效的，因为接口报错的时候根本就没走进响应拦截里面去。而且走到响应拦截的error里面，所以目前就在error这里处理接口错误逻辑了emmm


  ## lzm0x219

  对的，之前版本不会的

```
