# umi@4 errorHandler 会继续抛出异常

<!--
⚠️ ⚠️ ⚠️ 注意：讨论和提问请到讨论区（https://github.com/umijs/umi/discussions），否则会被直接关掉。 ⚠️ ⚠️ ⚠️
-->
<!--
感谢您向我们反馈问题，为了高效的解决问题，我们期望你能提供以下信息：
-->

## What happens?

<!-- A clear and concise description of what the bug is. -->
<!-- 清晰的描述下遇到的问题。-->

接口返回 504，定义了 errorHandler 会继续抛异常出来，我必须在 request 后手动 catch 住才行

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

<!-- 为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN -->
<!-- https://github.com/YOUR_REPOSITORY_URL -->

应该是这里的插件代码，但是这样设计 errorHandler 很不好用啊，可以通过 errorHandler 里面 return 来判断一下是否继续抛吗，现在需要封装一下 request 方法
![image](https://user-images.githubusercontent.com/37258382/178746175-0d7bb7de-2dd1-431d-83b9-c1e555370a66.png)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

<!-- 请提供复现链接/步骤，错误日志以及相关配置 -->

## Context

- **Umi Version**:
- 4
- **Node Version**:
- 16.16.0
- **Platform**:
- macOS

## tolerance-go

加2个注释帮助大家理解
![image](https://user-images.githubusercontent.com/37258382/178754090-184a62a2-70de-4440-9a44-9807ae16a74c.png)

如果希望前端能获取统一的数据格式请求返回，我这里分享一下封装（我没有用 useRequest）
<img width="531" alt="image" src="https://user-images.githubusercontent.com/37258382/186208543-de279968-1a69-490a-ab92-c9ec4b9f1f85.png">

## LanJamRom

umi3中request的错误处理逻辑不会影响最终传递给页面的数据格式，但现在得额外增加try catch才能保证程序继续执行下去

## imoxuan

确实存在这个问题，官方有没有统一处理的想法？

## ChrisLuckComes

多谢老哥，确实有问题，按你的先做了

## jkiss

貌似 `!200` 的 `status` 只能通过 `try catch` 来获取 🤔

## July-ing

`可以通过errorHandler里面的return 来判断一下是否继续抛吗` 不抛错误的话，是想resolve还是代码停住呢？

## tolerance-go

我现在用 ahooks@3 + axios 单独做请求了，暂时放弃 max 里面的 request 了

## tolerance-go

继续 throw 是因为 useRequest 需要 reject 吧

## liuqiandev

1、errorHandler只能处理httpstatus != 200 的请求
2、如果业务异常但httpstatus == 200的话 在responseInterceptors中处理
3、如果用useRequest的话，在app.ts中将useRequest的默认设置改成如下：

```
const RequestProvider = ({ children }: any) => {
  return <UseRequestProvider value={{throwOnError:true}}>{children}</UseRequestProvider>
}

export function rootContainer(container: any) {
  return React.createElement(RequestProvider, {}, container);
}
```

## matrixyf

这个算是breaking change了吧，umi3里面umi-request的errorHandler会自动捕获异常，不再传递异常给dva；但到了umi4，通过在app.ts中配置了request的errorHandler，异常会一直传递，导致dva执行中断。

我通过在app.ts配置解决了这个问题，要不然就得在dva里面每次call的时候都加一遍try catch

```
export const dva = {
  config: {
    onError(e: any) {
      e.preventDefault();
      console.error(e.message);
    },
  },
};
```
